# Obter a lista de andamento
GET http://localhost:3000/api/andamento
Content-Type: application/json
###

# Inserir novo andamento
POST http://localhost:3000/api/andamento
Content-Type: application/json

{
"dataHora": "2022-03-26",
 "titulo": "teste andamento",
 "descricao": "Teste3",
 "colaborador":"623e490358a3afc5d1561612",
  "atividade":"6244f9ca7718c59b0ebec35e"
}
###

# andamento sem titulo requerido.
POST http://localhost:3000/api/andamento
Content-Type: application/json

{
"dataHora": "2022-03-26",
 "titulo": "",
 "descricao": "Inicio",
 "colaborador":"623e490358a3afc5d1561612",
  "atividade":"6244f9ca7718c59b0ebec35e"
}
###

# Alterar andamento
PUT http://localhost:3000/api/andamento
Content-Type: application/json

{
  "_id": "6244fadf3a3a135958a42e00",
    "dataHora": "2022-03-26T00:00:00.000Z",
    "titulo": "teste andamento",
    "descricao": "Teste teste",
    "colaborador": "623e490358a3afc5d1561612",
    "atividade": "6244f9ca7718c59b0ebec35e"
}
###

# Excluir um andamento
DELETE http://localhost:3000/api/andamento/6244faa53a3a135958a42dfb
Content-Type: application/json
###

# Obter pelo id do andamento
GET http://localhost:3000/api/andamento/6244fadf3a3a135958a42e00
Content-Type: application/json
###

# Obter andamento filtrando
GET http://localhost:3000/api/andamento/filtro/Teste
Content-Type: application/json
###