# Obter a lista de atividade
GET http://localhost:3000/api/atividade
Content-Type: application/json
###

# Inserir novo atividade
POST http://localhost:3000/api/atividade
Content-Type: application/json

{
 "titulo": "teste", 
 "descricao": "teste atividade2",
 "status": "Inicio",
 "prazo": "2022-03-26",
 "agendaInicio":"2022-03-26",
 "dataHoraTermino":"2022-03-26",
 "requisicao":"623e676f3c045dd27b0851b2",
 "colaborador":"623e490358a3afc5d1561612"
}
###

# atividade sem titulo requerido.
POST http://localhost:3000/api/atividade
Content-Type: application/json

{
 "titulo": "", 
 "descricao": "teste atividade",
 "status": "Inicio",
 "prazo": "2022-03-26",
 "agendaInicio":"2022-03-26",
 "dataHoraTermino":"2022-03-26",
 "requisicao":"623e676f3c045dd27b0851b2",
 "colaborador":"623e490358a3afc5d1561612"
}
###

# Alterar atividade
PUT http://localhost:3000/api/atividade
Content-Type: application/json

{
   "titulo": "teste",
  "descricao": "teste atividade alterado",
  "status": "Inicio",
  "prazo": "2022-03-26T00:00:00.000Z",
  "agendaInicio": "2022-03-26T00:00:00.000Z",
  "dataHoraTermino": "2022-03-26T00:00:00.000Z",
  "requisicao": "623e676f3c045dd27b0851b2",
  "colaborador": "623e490358a3afc5d1561612",
  "_id": "6244f9ca7718c59b0ebec35e"
}
###

# Excluir uma atividade
DELETE http://localhost:3000/api/atividade/6244f9b07718c59b0ebec35b
Content-Type: application/json
###

# Obter pelo id da atividade
GET http://localhost:3000/api/atividade/6244f9ca7718c59b0ebec35e
Content-Type: application/json
###

# Obter atividade filtrando
GET http://localhost:3000/api/atividade/filtro/teste 
Content-Type: application/json
###