# Obter a lista de requisicao
GET http://localhost:3000/api/requisicao
Content-Type: application/json
###

# Inserir novo requisicao
POST http://localhost:3000/api/requisicao
Content-Type: application/json

{
"titulo": "Teste2",
"descricao":"Teste",
"dataHoraCriada": "2022-03-25",
"status": "Inicio",
"prazoAtendimento": "2022-03-26",
"tipoRequisicao": "623e5662395410d5d2a64696",
"solicitante":"623e508da3fbde374ba18c23"
}
###

# colaborador sem nome requerido.
POST http://localhost:3000/api/requisicao
Content-Type: application/json

{
 "nome": "",
 "email": "135966@upf.br",
 "senha": "123",
}
###

# colaborador com email duplicado.
POST http://localhost:3000/api/requisicao
Content-Type: application/json

{
 "nome": "Daniele",
 "email": "135966@upf.br",
 "senha": "123",
}
###

# Alterar colaborador
PUT http://localhost:3000/api/requisicao
Content-Type: application/json

{
 "_id": "623e403951728b9a00efedce",
 "nome": "Daniele alterado",
 "email": "135966@testeteste.com",
  "senha": "123"
}
###

# Excluir um colaborador
DELETE http://localhost:3000/api/requisicao/623e431904b80d2556e49ce5
Content-Type: application/json
###

# Obter pelo id de colaborador
GET http://localhost:3000/api/requisicao/623e490358a3afc5d1561612
Content-Type: application/json
###

# Obter colaborador filtrando
GET http://localhost:3000/api/requisicao/filtro/Daniele
Content-Type: application/json
###