# Obter a lista de requisicao
GET http://localhost:3000/api/requisicao
Content-Type: application/json
###

# Inserir novo requisicao
POST http://localhost:3000/api/requisicao
Content-Type: application/json

{
"titulo": "Teste2",
"descricao":"Teste",
"dataHoraCriada": "2022-03-25",
"status": "Inicio",
"prazoAtendimento": "2022-03-26",
"tipoRequisicao": "623e5662395410d5d2a64696",
"solicitante":"623e508da3fbde374ba18c23"
}
###

# Alterar requisicao
PUT http://localhost:3000/api/requisicao
Content-Type: application/json

{
 "_id": "623e676f3c045dd27b0851b2",
  "titulo": "Teste altera requisicao",
  "descricao": "Teste",
  "dataHoraCriada": "2022-03-25T00:00:00.000Z",
  "status": "Inicio",
  "prazoAtendimento": "2022-03-26T00:00:00.000Z",
  "tipoRequisicao": "623e5662395410d5d2a64696",
  "solicitante": "623e508da3fbde374ba18c23"
}
###

# Excluir uma requisicao
DELETE http://localhost:3000/api/requisicao/6244f82b0405f645d9e88a7e
Content-Type: application/json
###

# Obter pelo id da requisicao
GET http://localhost:3000/api/requisicao/623e676f3c045dd27b0851b2
Content-Type: application/json
###

# Obter requisicao filtrando
GET http://localhost:3000/api/requisicao/filtro/altera
Content-Type: application/json
###