# Obter a lista de colaborador
GET http://localhost:3000/colaborador
Content-Type: application/json
###

# Inserir novo colaborador
POST http://localhost:3000/colaborador
Content-Type: application/json

{
 "nome": "Teste Excluir",
 "email": "teste@upf.br",
 "senha": "12345"
}
###

# Alterar um colaborador
PUT http://localhost:3000/colaborador
Content-Type: application/json

{
    "_id": "622be6062987518f1ccf74bb",
    "nome": "Teste222",
    "email": "teste@upf.br",
    "senha": "12345"
}
###

# Excluir um colaborador pelo id
DELETE http://localhost:3000/colaborador/622be6f42987518f1ccf74bc
Content-Type: application/json
###

# Obter colaborador pelo id
GET http://localhost:3000/colaborador/622be5f72987518f1ccf74ba
Content-Type: application/json
###

 #Obter colaborador filtrando
GET http://localhost:3000/colaborador/filtro/teste
Content-Type: application/json
###